const skills = [
  {
    id: 1,
    character: "Hein",
    name: "Tear Up",
    image: "../../assets/skillsImgs/tear-Up.png",
    targetting: "Single Enemy",
    cost: "Cost: 1 mana",
    stats01: "Damage: 15 - Accuracy: 84% - Critical Hit: 0%.",
    Countdown: "Countdown 1.",
    IgnoreTaunt: "Ignore Taunt.",
    "Cannot be fixed": "Cannot be fixed.",
    castEffectLine01: "- Always lands against targets with a Weakening debuff.",
    castEffectLine02: "- Attack an additional enemy with the lowest health.",
    castEffectLine03: "- If Facing one enemy, damage is increased by 7.",
    synergies: ["Countdown", "Ignore Taunt", "Attack"],
  },
  {
    id: 2,
    character: "Hein",
    name: "Mutilate",
    image: "../../assets/skillsImgs/mutilate.png",
    targetting: "Random Enemy",
    cost: "x mana",
    stats01: "Damage: 27 - Accuracy: 96% - Critical Hit: 0%.",
    PriorityLowHP: "Priority Low HP",
    Overload: "Overload",
    synergies: ["Priority Low HP", "Overload", "Attack"],
  },
  {
    id: 3,
    character: "Hein",
    name: "Identify Weakness",
    image: "../../assets/skillsImgs/identify-Weakness.png",
    targetting: "Single Enemy",
    cost: "x mana",
    stats02: "Debuff Success: 150% - Stacks inflicted: (2/2)",
    Once: "Once",
    Swiftness: "Swiftness",
    DetectWeakness: "Detect Weakness",
    castEffectLine01: "- Inflicts Detect Weakness.png",
    castEffectLine02: "- Each stack inflicts an instance of the debuff",
    synergies: ["Once", "Switness", "Detect-Weakness", "Debuff"],
  },
  {
    id: 4,
    character: "Hein",
    name: "Assault Slash",
    image: "../../assets/skillsImgs/assault-Slash.png",
    targetting: "All Enemies",
    cost: "x mana",
    stats01: "Damage: 18 - Accuracy: 80% - critical Hit: -10%",
    Countdown: "Countdown 01",
    Overload: "Overload",
    castEffectLine01: "- Always lands against targets with a weakening debuff.",
    castEffectLine02: "- If Facing one enemy, damage is increased by 7.",
    synergies: ["Countdown", "Overload", "Debuff"],
  },
  {
    id: 5,
    character: "Hein",
    name: "Intimidation",
    image: "../../assets/skillsImgs/",
    targetting: "All Enemies",
    cost: "x mana",
    stats01: "Damage: 5 - Accuracy: 102% - critical Hit: 0%",
    stats02: " Debuff Success Chance: 150% - Stacks Inflicted",
    Swiftness: "Swiftness",
    Fear: "Fear",
    synergies: ["Once", "Switness", "Debuff"],
  },
  {
    id: 6,
    character: "Hein",
    name: "Blood Reflux",
    image: "../../assets/skillsImgs/",
    targetting: "Other Ally",
    cost: "x mana",
    stats01:
      "Damage: Missing healing guage - Accuracy: Guarenteed hit - critical Hit: N/A",
    stats02:
      " Debuff Success Chance: Guarenteed application - Stacks Inflicted (1/2)",
    Swiftness: "Swiftness",
    Bloodthirst: "Bloodthirst",
    Tenacity: "Tenacity",
    PainDamage: "Pain Damage",
    RestoreHealingGauge: "Restore Healing Gauge",
    castEffectLine01:
      "- Restore the target's healing guage but receive Pain damage equal to half of the amount.",
    castEffectLine02: "- Inflicts the Target with Bloodthirst",
    castEffectLine03: "- Inflicts Target with Tenacity",
    synergies: [
      "Switness",
      "Bloodthirst",
      "Tenacity",
      "Pain Damage",
      "Heal - Guage",
      "Buff",
    ],
  },
];
export default skills;
